[tool.ruff]
line-length = 120
select = ["F", "E", "W", "I"]

[tool.ruff.isort]
known-first-party = ["backend"]
combine-as-imports = true
case-sensitive = false
force-sort-within-sections = true
lines-after-imports = 2

[tool.isort]
profile = "ruff"
line_length = 120
known_first_party = ["backend"]
force_sort_within_sections = true
combine_as_imports = true
